# Generated by Django 4.0.2 on 2022-03-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0003_alter_cargo_options_alter_cargo_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
