# Generated by Django 4.0.2 on 2022-03-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0005_empleado_cedula_alter_cargo_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
